module Setting
  EMAIL     = ENV.fetch("TALENTLESS_EMAIL")
  PASSWORD  = ENV.fetch("TALENTLESS_PASSWORD")
  LATITUDE  = ENV.fetch("TALENTLESS_LATITUDE").to_f
  LONGITUDE = ENV.fetch("TALENTLESS_LONGITUDE").to_f
  TIME_ZONE = ENV.fetch("TALENTLESS_TIME_ZONE", "+07:00")
  HEADLESS  = ENV["TALENTLESS_HEADLESS"] == "true"
end
